### ISSUE TITLE
secregent-gen package cannot be installed using --install-package parameter at bootstrap

### ISSUE THREAD

**Issue by cmoulliard** [vmware-tanzu/community-edition#4511] opened 2022-05-12 08:34 UTC
## Issue

TCE supports to install packages since 0.12 at bootstrap but that will fail if we try to install `secretgen-controller ` 

``` 
tanzu uc create test --install-package cert-manager --install-package secretgen-controller:0.7.1
...
🌐 Installing package cert-manager
   Selected package cert-manager.community.tanzu.vmware.com
   Installing package without version specified. Using version 1.8.0
   Installing package with no configuration file

🌐 Installing package secretgen-controller
   WARNING: failed to install package secretgen-controller. Error: no package was resolved for name secretgen-controller with version 0.7.1
✅ Cluster created

🎮 kubectl context set to test

View available packages:
   tanzu package available list
View running pods:
   kubectl get po -A
Delete this cluster:
   tanzu unmanaged delete test
```

## Problem

This problems occurs as the `secretgen-controller ` package is part of the core packages installed under the `tkg-system` namespace

## Versions

TCE: 0.12

**Comment by jpmcb** [comment] 2022-05-12 14:02
I _believe_ this is because `secretgen-controller` is in the core package repository and if I'm remember correctly, we only do installs during bootstrapping from the user managed repo; will have to test this out however 👀

**Comment by jpmcb** [comment] 2022-05-12 19:15
Duplicate of: https://github.com/vmware-tanzu/community-edition/issues/4165

**Closed** 2022-05-12 19:17 UTC
Labels: kind/bug, triage/needs-triage
