### ISSUE TITLE
[Docs] [](/docs/latest/cli-installation/)

### ISSUE THREAD

**Issue by Luckeyd** [vmware-tanzu/community-edition#2389] opened 2021-10-28 19:27 UTC
## Description

Documentation error in the Windows installation procedures at https://tanzucommunityedition.io/docs/latest/cli-installation/

## Location
https://tanzucommunityedition.io/docs/latest/cli-installation/

Step 4: Open PowerShell as an administrator and run the following:
choco install tanzu-community-edition --version=v0.9.1

Running this commend generates the following error:
'v0.9.1' is not a valid version string.
Parameter name: version

This step should read:
'choco install tanzu-community-edition --version=0.9.1'
'Remove the "v" in the version number.'

**Comment by stmcginnis** [comment] 2021-11-02 16:39
Thanks, someone is looking at this now. Closing this issue though as a duplicate of https://github.com/vmware-tanzu/community-edition/issues/2382

**Closed by stmcginnis** 2021-11-02 16:39 UTC
Labels: triage/needs-triage, kind/docs
