### ISSUE TITLE
Docs site bumped versions of TCE pre-maturely.

### ISSUE THREAD

**Issue by joshrosso** [vmware-tanzu/community-edition#3144] opened 2022-02-15 14:11 UTC
Before releasing TCE, the website updated its references to the newest version.

![image](https://user-images.githubusercontent.com/6200057/154078774-3bd9b893-f3a7-458e-9529-affae028f26a.png)

This should not happen until we officially GA. We likely should move to a model where the version is driven by a value in a YAML file, rather than an automated PR.

**Comment by stmcginnis** [comment] 2022-02-15 15:09
This is a duplicate of https://github.com/vmware-tanzu/community-edition/issues/3143

**Comment by jpmcb** [comment] 2022-02-15 17:00
Looks like this was done by TCE automation in our YAML config: https://github.com/vmware-tanzu/community-edition/pull/3138/files

**Comment by jpmcb** [comment] 2022-02-15 17:02
Closing in favor of #3143

**Closed by jpmcb** 2022-02-15 17:02 UTC
Labels: kind/bug, triage/needs-triage
