### ISSUE TITLE
Command to create a management cluster fails when copy & pasted into CLI, lacking `CLUSTER_PLAN`

### ISSUE THREAD

**Issue by rheaton** [vmware-tanzu/community-edition#2159] opened 2021-10-05 17:39 UTC
## Bug Report

When using the command generated by the web UI to create a management cluster, it fails to create the cluster when copy & pasted into CLI. The (truncated) error message:
```
$ tanzu management-cluster create --file /Users/me/.config/tanzu/tkg/clusterconfigs/up3yeggwm7.yaml -v 6
compatibility file (/Users/me/.config/tanzu/tkg/compatibility/tkg-compatibility.yaml) already exists, skipping download
BOM files inside /Users/me/.config/tanzu/tkg/bom already exists, skipping download
CEIP Opt-in status: false

Validating the pre-requisites...
Error: configuration validation failed: required config variable 'CLUSTER_PLAN' is not set
Usage:
  tanzu management-cluster create [flags]
...
```

When proceeding to use the web UI, the cluster can be created.

## Expected Behavior

I would expect the command to succeed and be ready to run without additional flags.

## Steps to Reproduce the Bug

Use the UI to create the management cluster command, copy/paste into CLI.

## Screenshots or additional information and context

up3yeggwm7.yaml
```yaml
CLUSTER_CIDR: 100.96.0.0/11
CLUSTER_NAME: bill
ENABLE_MHC: "false"
IDENTITY_MANAGEMENT_TYPE: none
INFRASTRUCTURE_PROVIDER: docker
LDAP_BIND_DN: ""
LDAP_BIND_PASSWORD: ""
LDAP_GROUP_SEARCH_BASE_DN: ""
LDAP_GROUP_SEARCH_FILTER: ""
LDAP_GROUP_SEARCH_GROUP_ATTRIBUTE: ""
LDAP_GROUP_SEARCH_NAME_ATTRIBUTE: cn
LDAP_GROUP_SEARCH_USER_ATTRIBUTE: DN
LDAP_HOST: ""
LDAP_ROOT_CA_DATA_B64: ""
LDAP_USER_SEARCH_BASE_DN: ""
LDAP_USER_SEARCH_FILTER: ""
LDAP_USER_SEARCH_NAME_ATTRIBUTE: ""
LDAP_USER_SEARCH_USERNAME: userPrincipalName
OIDC_IDENTITY_PROVIDER_CLIENT_ID: ""
OIDC_IDENTITY_PROVIDER_CLIENT_SECRET: ""
OIDC_IDENTITY_PROVIDER_GROUPS_CLAIM: ""
OIDC_IDENTITY_PROVIDER_ISSUER_URL: ""
OIDC_IDENTITY_PROVIDER_NAME: ""
OIDC_IDENTITY_PROVIDER_SCOPES: ""
OIDC_IDENTITY_PROVIDER_USERNAME_CLAIM: ""
OS_ARCH: ""
OS_NAME: ""
OS_VERSION: ""
SERVICE_CIDR: 100.64.0.0/13
TKG_HTTP_PROXY_ENABLED: "false"
```

## Environment Details

* Build version (`tanzu version`): 
```
version: v0.2.1
buildDate: 2021-09-29
sha: ceaa474
```
* Deployment (Managed/Standalone cluster): 
management cluster
* Infrastructure Provider (Docker/AWS/Azure/vSphere): 
Docker Desktop with 8 CPU, 12GB mem, 2GB swap, 60GB disk
* Operating System (client):
Mac OS 11.6

**Comment by stmcginnis** [comment] 2021-10-05 17:41
Hey @miclettej - can you take a look?

If the `CLUSTER_PLAN` value is required, I think we either need to get the UI to populate that in the generated yaml file, or the command line that the UI provides should be updated to prepend `CLUSTER_PLAN=dev tanzu management-cluster...`.

Thoughts?

**Comment by miclettej** [comment] 2021-10-05 17:44
@stmcginnis yes we'll get right on it. Thanks! This looks like it might be some kind of regression. This issue would have likely been picked up on long back. We'll dig into it.

**Comment by jpmcb** [comment] 2021-10-05 18:13
@miclettej - should the UI have populated the `CLUSTER_PLAN` field in the config file? Or is that not a value that is anticipated to be populated in the config file?

**Comment by miclettej** [comment] 2021-10-05 18:19
@jpmcb I checked with a few other folks and CLUSTER_PLAN should get set in the config file. Checking the vSphere workflow to see if it's being set.

**Comment by stmcginnis** [comment] 2021-10-05 18:31
I confirmed the behavior on my system. Deploying management cluster using the Docker provider. Freshly cleaned up system, running the TCE 0.9.1 release. Went through the couple steps in the UI, then copied the provided command and pasted into my terminal. I got the same error, and looking at the generated yaml file, there indeed was no `CLUSTER_PLAN` listed there.

**Comment by miclettej** [comment] 2021-10-05 18:48
@jpmcb The UI is not sending the cluster plan in the payload to generate the config file, I believe because we don't offer the user an option for dev vs. prod. The issue is that I'm not seeing a default 'dev' being set on the backend around `tkgconfigproviders/docker.go` for example

**Comment by jpmcb** [comment] 2021-10-12 19:27
Looks like the above PR merged - we will get this pulled in on the next release!

**Comment by berlin-ab** [comment] 2021-11-13 00:03
Related - is there a way to list the available plans? The value 'dev' was referenced in the docs, or I would have had no idea what the possible values are.

**Comment by jpmcb** [comment] 2022-01-31 23:05
Hi @berlin-ab, I don't believe there's a way right now to list the available cluster plans. If that sounds like something you'd like to propose a feature for, head over to the https://github.com/vmware-tanzu/tanzu-framework and file an issue!

**Comment by joshrosso** [comment] 2022-03-04 20:35
@stmcginnis since this should be in our next framework release, I'm assigning it to you to validate.

If you could do a build off main, you should be able to validate this and close it or state more work is required.

Thanks!

**Comment by stmcginnis** [comment] 2022-03-04 22:04
Built off of `main` (the soon to be release v0.11.0 code).

Launched management cluster creation UI: `tanzu management-cluster create --ui`
Followed the wizard to deploy a management cluster.
On final review page, copied the cli command to run.

Resulting config file:
```yaml
CLUSTER_CIDR: 100.96.0.0/11
CLUSTER_NAME: gh2159
CLUSTER_PLAN: dev
ENABLE_MHC: "false"
IDENTITY_MANAGEMENT_TYPE: none
INFRASTRUCTURE_PROVIDER: docker
LDAP_BIND_DN: ""
LDAP_BIND_PASSWORD: ""
LDAP_GROUP_SEARCH_BASE_DN: ""
LDAP_GROUP_SEARCH_FILTER: ""
LDAP_GROUP_SEARCH_GROUP_ATTRIBUTE: ""
LDAP_GROUP_SEARCH_NAME_ATTRIBUTE: cn
LDAP_GROUP_SEARCH_USER_ATTRIBUTE: DN
LDAP_HOST: ""
LDAP_ROOT_CA_DATA_B64: ""
LDAP_USER_SEARCH_BASE_DN: ""
LDAP_USER_SEARCH_FILTER: ""
LDAP_USER_SEARCH_NAME_ATTRIBUTE: ""
LDAP_USER_SEARCH_USERNAME: userPrincipalName
OIDC_IDENTITY_PROVIDER_CLIENT_ID: ""
OIDC_IDENTITY_PROVIDER_CLIENT_SECRET: ""
OIDC_IDENTITY_PROVIDER_GROUPS_CLAIM: ""
OIDC_IDENTITY_PROVIDER_ISSUER_URL: ""
OIDC_IDENTITY_PROVIDER_NAME: ""
OIDC_IDENTITY_PROVIDER_SCOPES: ""
OIDC_IDENTITY_PROVIDER_USERNAME_CLAIM: ""
OS_ARCH: ""
OS_NAME: ""
OS_VERSION: ""
SERVICE_CIDR: 100.64.0.0/13
TKG_HTTP_PROXY_ENABLED: "false"
```

Ran the copied creation command line: `tanzu management-cluster create gh2159  --file /Users/smcginnis/.config/tanzu/tkg/clusterconfigs/l78cgvpu9i.yaml -v 6`

Management cluster deployed successfully.

Looks like we can close this. If you still see any issues with the v0.11.0 release, please either reopen this issue or file a new one. Sorry it has taken so long to address. We are hoping to get to our plan of more frequent releases now that we've gotten some things in place.

**Closed by stmcginnis** 2022-03-04 22:04 UTC
Labels: kind/bug, area/framework
