### ISSUE TITLE
On Windows, Tanzu Cluster create command fails to utilise cluster name from cli

### ISSUE THREAD

**Issue by vandalix1** [vmware-tanzu/community-edition#2255] opened 2021-10-14 07:44 UTC
## Bug Report

On Windows 10 (10.0.19043) running TCE 0.9.1 and attempting to deploy onto a WSL2 docker environment, when utilising the tanzu management-cluster create command as per documentation

tanzu management-cluster create -i docker [CLUSTER-NAME]
also tried
tanzu management-cluster create [CLUSTER-NAME] -i docker 

the cluster name does not get instantiated.  It uses a "default name" - tkg-mgmt-docker-202110xxxxxxxxxxxx
WORKAROUND : 
If i issue an environmental variable 
set CLUSTER_NAME=<CLUSTER_NAME>
then it uses this as the cluster name and ignores whatever is input as part of the CLI command.

## Expected Behavior

Expected to create a Management Cluster with the cluster name specified in the cli command

## Steps to Reproduce the Bug

Install TCE 0.9.1 on Windows 10
Install Kubectl 
Follow instructions as per here : https://tanzucommunityedition.io/docs/latest/ref-windows-capd/ 

## Environment Details

* Build version (`tanzu version`):  0.9.1
* Deployment (Managed/Standalone cluster):  Managed
* Infrastructure Provider (Docker/AWS/Azure/vSphere):  Docker on Windows (and WSL2)
* Operating System (client): Windows 10
* wsl running kernel :  Linux nchan-z01 5.4.72-microsoft-standard-WSL2+ #1 SMP Thu Oct 7 05:45:22 UTC 2021 x86_64 Linux
* wsl zgrep CONFIG_NETFILTER_XT_TARGET_CT /proc/config.gz :  CONFIG_NETFILTER_XT_TARGET_CT=y

## Diagnostics and log bundle

C:\>tanzu management-cluster create -i docker ncc

Validating the pre-requisites...
Identity Provider not configured. Some authentication features won't work.

Setting up management cluster...
Validating configuration...
Using infrastructure provider docker:v0.3.23
Generating cluster configuration...
Setting up bootstrapper...
Bootstrapper created. Kubeconfig: C:\Users\nchan\.kube-tkg\tmp\config_tFL2IsKs
Installing providers on bootstrapper...
Fetching providers
Installing cert-manager Version="v1.1.0"
Waiting for cert-manager to be available...
Installing Provider="cluster-api" Version="v0.3.23" TargetNamespace="capi-system"
Installing Provider="bootstrap-kubeadm" Version="v0.3.23" TargetNamespace="capi-kubeadm-bootstrap-system"
Installing Provider="control-plane-kubeadm" Version="v0.3.23" TargetNamespace="capi-kubeadm-control-plane-system"
Installing Provider="infrastructure-docker" Version="v0.3.23" TargetNamespace="capd-system"
Start creating management cluster...
Saving management cluster kubeconfig into C:\Users\nchan/.kube/config

Failure while deploying management cluster, Here are some steps to investigate the cause:

Debug:
    kubectl get po,deploy,cluster,kubeadmcontrolplane,machine,machinedeployment -A --kubeconfig C:\Users\nchan\.kube-tkg\tmp\config_tFL2IsKs
    kubectl logs deployment.apps/<deployment-name> -n <deployment-namespace> manager --kubeconfig C:\Users\nchan\.kube-tkg\tmp\config_tFL2IsKs

To clean up the resources created by the management cluster:
          tanzu management-cluster delete
Error: unable to set up management cluster: unable to get management cluster client: unable to get client: Failed to invoke API on cluster : Get "https://172.18.0.3:6443/version?timeout=32s": dial tcp 172.18.0.3:6443: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.
←[1mUsage:←[0m
  tanzu management-cluster create [flags]

←[1mExamples:←[0m

    # Create a management cluster on AWS infrastructure, initializing it with
    # components required to create workload clusters through it on the same infrastructure
    # by bootstrapping through a self-provisioned bootstrap cluster.
    tanzu management-cluster create --file ~/clusterconfigs/aws-mc-1.yaml
    # Launch an interactive UI to configure the settings necessary to create a
    # management cluster
    tanzu management-cluster create --ui
    # Create a management cluster on vSphere infrastructure by using an existing
    # bootstrapper cluster. The current kube context should point to that
    # of the existing bootstrap cluster.
    tanzu management-cluster create --use-existing-bootstrap-cluster --file vsphere-mc-1.yaml

←[1mFlags:←[0m
  -b, --bind string                      Specify the IP and port to bind the Kickstart UI against (e.g. 127.0.0.1:8080). (default "127.0.0.1:8080")
      --browser string                   Specify the browser to open the Kickstart UI on. Use 'none' for no browser. Defaults to OS default browser. Supported: ['chrome', 'firefox', 'safari', 'ie', 'edge', 'none']
      --dry-run                          Generates the management cluster manifest and writes the output to stdout without applying it
  -f, --file string                      Configuration file from which to create a management cluster
      --force-config-update              Force an update of all configuration files in ${HOME}/.config/tanzu/tkg/bom and ${HOME}/.tanzu/tkg/compatibility
  -h, --help                             help for create
  -t, --timeout duration                 Time duration to wait for an operation before timeout. Timeout duration in hours(h)/minutes(m)/seconds(s) units or as some combination of them (e.g. 2h, 30m, 2h30m10s) (default 30m0s)
  -u, --ui                               Launch interactive management cluster provisioning UI
  -e, --use-existing-bootstrap-cluster   Use an existing bootstrap cluster to deploy the management cluster
  -y, --yes                              Create management cluster without asking for confirmation

←[1mGlobal Flags:←[0m
      --log-file string   Log file path
  -v, --verbose int32     Number for the log level verbosity(0-9)

Error: exit status 1

✖  exit status 1

<Fix the .kube\config file> then :

C:\>tanzu management-cluster get
  ←[1mNAME                          ←[0m  ←[1mNAMESPACE ←[0m  ←[1mSTATUS←[0m  ←[1mCONTROLPLANE←[0m  ←[1mWORKERS←[0m  ←[1mKUBERNETES      ←[0m  ←[1mROLES     ←[0m
  tkg-mgmt-docker-20211014174852  tkg-system  failed  1/1           0/1      v1.21.2+vmware.1  management

Details:

NAME                                                                               READY  SEVERITY  REASON  SINCE  MESSAGE
/tkg-mgmt-docker-20211014174852                                                    True                     8m44s
├─ClusterInfrastructure - DockerCluster/tkg-mgmt-docker-20211014174852             True                     9m29s
├─ControlPlane - KubeadmControlPlane/tkg-mgmt-docker-20211014174852-control-plane  True                     8m44s
│ └─Machine/tkg-mgmt-docker-20211014174852-control-plane-bmg9z                     True                     8m45s
└─Workers
  └─MachineDeployment/tkg-mgmt-docker-20211014174852-md-0
    └─Machine/tkg-mgmt-docker-20211014174852-md-0-5b4798589c-rh2bb                 True                     8m4s

Providers:

  ←[1mNAMESPACE                        ←[0m  ←[1mNAME                 ←[0m  ←[1mTYPE                  ←[0m  ←[1mPROVIDERNAME←[0m  ←[1mVERSION←[0m  ←[1mWATCHNAMESPACE←[0m
  capd-system                        infrastructure-docker  InfrastructureProvider  docker        v0.3.23
  capi-kubeadm-bootstrap-system      bootstrap-kubeadm      BootstrapProvider       kubeadm       v0.3.23
  capi-kubeadm-control-plane-system  control-plane-kubeadm  ControlPlaneProvider    kubeadm       v0.3.23
  capi-system                        cluster-api            CoreProvider            cluster-api   v0.3.23

**Comment by stmcginnis** [comment] 2021-11-10 14:33
Sorry for the delay updating. I think this was due to an issue that has been found and addressed in the `tanzu-framework` code. Before we do the next release we will update the version of `tanzu-framework` we are using and should pick up the fix.

Keeping this issue here so we can make sure to validate the fix is working as expected.

**Comment by seemiller** [comment] 2022-01-24 21:09
Closing - duplicate of https://github.com/vmware-tanzu/community-edition/issues/2134

**Closed by seemiller** 2022-01-24 21:09 UTC
Labels: kind/bug, area/framework
