### ISSUE TITLE
tanzu cli version doesn't match released version

### ISSUE THREAD

**Issue by iguyking** [vmware-tanzu/community-edition#2410] opened 2021-10-30 01:40 UTC
## Bug Report

Just installed tanzu 0.9.1 release to test and when I run tanzu.exe the version is v0.2.1
```
❯  tanzu version
version: v0.2.1
buildDate: 2021-09-29
sha: ceaa474
```

## Expected Behavior

That the CLI says it's version 0.9.1

## Steps to Reproduce the Bug

Install and run `tanzu version`

## Environment Details

* Build version (`tanzu version`):  buildDate: 2021-09-29
* Deployment (Managed/Standalone cluster): 
* Infrastructure Provider (Docker/AWS/Azure/vSphere):  
* Operating System (client):  Windows 10

**Comment by stmcginnis** [comment] 2021-11-10 21:47
This is actually correct since the `tanzu` CLI we use is from the v0.2.1 release of `tanzu-framework`.

There is an open item to expand this version output to include other components where we could have something better indicate which version of TCE is being used.

Going to close this as a duplicate of https://github.com/vmware-tanzu/tanzu-framework/issues/36

**Closed by stmcginnis** 2021-11-10 21:47 UTC
Labels: kind/bug, triage/needs-triage
