### ISSUE TITLE
TCE v0.10.0 is throwing error when deploying Management Cluster using NSX ALB v20.1.7

### ISSUE THREAD

**Issue by alinahid477** [vmware-tanzu/community-edition#3610] opened 2022-03-20 22:17 UTC
## Bug Report

TCE TKG v0.10.0 is throwing error when deploying Management Cluster using NSX ALB v20.1.7 as load balancer.

## Expected Behavior

Management cluster should be able to complete step: Generate cluster configuration

## Steps to Reproduce the Bug

on vSphere 7u2 environment start deployment of management cluster using the below config and it throws error at "Generate cluster configuration" step.

## Screenshots or additional information and context

✘ [0320 13:26:09.53627]: init.go:85] unable to set up management cluster, : unable to build management cluster configuration: unable to get template: - load: name crd not found in module static.lib.yaml in <toplevel> 03_customizations/02_avi/add_akoo.yaml:5 | #@ load("static.lib.yaml", "crd","service")

## Environment Details

* Build version (`tanzu version`): v0.10.0
* Deployment (Managed/Unmanaged cluster): Management Cluster
* Infrastructure Provider (Docker/AWS/Azure/vSphere): vSphere
* Operating System (client): Linux (ubuntu)

## Diagnostics and log bundle

✘ [0320 13:26:09.53627]: init.go:85] unable to set up management cluster, : unable to build management cluster configuration: unable to get template: - load: name crd not found in module static.lib.yaml in <toplevel> 03_customizations/02_avi/add_akoo.yaml:5 | #@ load("static.lib.yaml", "crd","service")

**Comment by stmcginnis** [comment] 2022-03-21 13:14
See https://github.com/vmware-tanzu/community-edition/issues/3189 for a workaround.

Waiting for someone with more expertise in this area to triage, but this is likely a duplicate of that one.

**Comment by stmcginnis** [comment] 2022-03-21 18:22
Looks like this was fixed in `tanzu-framework` with https://github.com/vmware-tanzu/tanzu-framework/pull/1044

That change is part of the tanzu-framework v0.11.2 release that TCE is using in the upcoming TCE v0.11.0 release, so this should be resolved then.

**Comment by joshrosso** [comment] 2022-04-12 00:27
@stmcginnis assigning this to you to validate once we have our first rc :+1:

**Comment by joshrosso** [comment] 2022-04-12 14:24
@stmcginnis on second though, now that we have a pinned framework version, can you verify this at your earliest and we can close it out? Appreciate it!

**Closed** 2022-04-12 15:00 UTC
Labels: kind/bug, area/packages, reporting/health/on-track
