### ISSUE TITLE
Windows installation using `install.bat` fails for `v0.11.0-rc.2`

### ISSUE THREAD

**Issue by aman556** [vmware-tanzu/community-edition#3735] opened 2022-03-25 08:47 UTC
## Bug Report
```
PS C:\Users\Administrator\tce-pkg\tce-windows-amd64-v0.11.0-rc.2\tce-windows-amd64-v0.11.0-rc.2> .\install.bat
        1 file(s) copied.
A subdirectory or file C:\Users\Administrator\.config\tanzu-plugins already exists.
default-local\discovery\standalone\builder.yaml
default-local\discovery\standalone\cluster.yaml
default-local\discovery\standalone\codegen.yaml
default-local\discovery\standalone\conformance.yaml
default-local\discovery\standalone\diagnostics.yaml
default-local\discovery\standalone\kubernetes-release.yaml
default-local\discovery\standalone\login.yaml
default-local\discovery\standalone\management-cluster.yaml
default-local\discovery\standalone\package.yaml
default-local\discovery\standalone\pinniped-auth.yaml
default-local\discovery\standalone\secret.yaml
default-local\discovery\standalone\unmanaged-cluster.yaml
default-local\distribution\windows\amd64\cli\builder\v0.11.2\tanzu-builder-windows_amd64.exe
default-local\distribution\windows\amd64\cli\cluster\v0.11.2\tanzu-cluster-windows_amd64.exe
default-local\distribution\windows\amd64\cli\codegen\v0.11.2\tanzu-codegen-windows_amd64.exe
default-local\distribution\windows\amd64\cli\conformance\v0.11.0-rc.2\tanzu-conformance-windows_amd64.exe
default-local\distribution\windows\amd64\cli\diagnostics\v0.11.0-rc.2\tanzu-diagnostics-windows_amd64.exe
default-local\distribution\windows\amd64\cli\kubernetes-release\v0.11.2\tanzu-kubernetes-release-windows_amd64.exe
default-local\distribution\windows\amd64\cli\login\v0.11.2\tanzu-login-windows_amd64.exe
default-local\distribution\windows\amd64\cli\management-cluster\v0.11.2\tanzu-management-cluster-windows_amd64.exe
default-local\distribution\windows\amd64\cli\package\v0.11.2\tanzu-package-windows_amd64.exe
default-local\distribution\windows\amd64\cli\pinniped-auth\v0.11.2\tanzu-pinniped-auth-windows_amd64.exe
default-local\distribution\windows\amd64\cli\secret\v0.11.2\tanzu-secret-windows_amd64.exe
default-local\distribution\windows\amd64\cli\unmanaged-cluster\v0.11.0-rc.2\tanzu-unmanaged-cluster-windows_amd64.exe
24 File(s) copied
Installing plugin 'builder:v0.11.2'
✔  successfully installed 'builder' plugin
Installing plugin 'codegen:v0.11.2'
✔  successfully installed 'codegen' plugin
Installing plugin 'cluster:v0.11.2'
✔  successfully installed 'cluster' plugin
Installing plugin 'kubernetes-release:v0.11.2'
✔  successfully installed 'kubernetes-release' plugin
Installing plugin 'login:v0.11.2'
✔  successfully installed 'login' plugin
Installing plugin 'management-cluster:v0.11.2'
Warning: Failed to initialize plugin '"management-cluster"' after installation. Downloading TKG compatibility file from 'projects.registry.vmware.com/tkg/framework-zshippable/tkg-compatibility'
Error: unable to ensure prerequisites: unable to ensure tkg BOM file: failed to download TKG compatibility file from the registry: failed to list TKG compatibility image tags: Get "https://projects.registry.vmware.com/v2/": x509: certificate signed by unknown authority
✔  successfully installed 'management-cluster' plugin
Installing plugin 'package:v0.11.2'
✔  successfully installed 'package' plugin
Installing plugin 'pinniped-auth:v0.11.2'
✔  successfully installed 'pinniped-auth' plugin
Installing plugin 'secret:v0.11.2'
✔  successfully installed 'secret' plugin
Installing plugin 'conformance:v0.11.0-rc.2'
✔  successfully installed 'conformance' plugin
Installing plugin 'diagnostics:v0.11.0-rc.2'
✔  successfully installed 'diagnostics' plugin
Installing plugin 'unmanaged-cluster:v0.11.0-rc.2'
✔  successfully installed 'unmanaged-cluster' plugin
        1 file(s) copied.
"Installation complete!"
"Please add C:\Program Files\tanzu permanently into your system's PATH."
PS C:\Users\Administrator\tce-pkg\tce-windows-amd64-v0.11.0-rc.2\tce-windows-amd64-v0.11.0-rc.2>
```

## Expected Behavior

`v0.11.0-rc.2` should install be without errors
## Steps to Reproduce the Bug

- Download the zip
- Extract it
- Run `install.bat`

## Environment Details

* Build version (`tanzu version`): v0.11.0-rc.2
* Deployment (Managed/Unmanaged cluster): 
* Infrastructure Provider (Docker/AWS/Azure/vSphere): 
* Operating System (client): Windows

**Comment by karuppiah7890** [comment] 2022-03-25 08:50
This got missed here https://github.com/vmware-tanzu/community-edition/runs/5681928606?check_suite_focus=true#step:3:144 😅

**Comment by karuppiah7890** [comment] 2022-03-25 08:52
Related / Duplicate - #1398

**Comment by joshrosso** [comment] 2022-03-28 19:03
Verified this is the same issue, however now the plugin's init get's triggered during install so it's surfacing.

![image](https://user-images.githubusercontent.com/6200057/160468447-3e71482e-9da0-4d4c-99da-aecff9ad49cb.png)

The cli is still installed correctly and users (on windows) may still need to use the following workaround:

https://github.com/vmware-tanzu/community-edition/issues/1398

**Comment by dvonthenen** [comment] 2022-03-28 19:56
I think this might be the solution to the problem... we shouldn't even be doing a `tanzu init` on the install in this package:
https://github.com/vmware-tanzu/community-edition/blob/main/hack/release/install.sh#L124-L126

**Comment by joshrosso** [comment] 2022-03-28 21:42
This behavior is a dupe of https://github.com/vmware-tanzu/community-edition/issues/1398

Verified that install still succeeds but you may need to do the workaround described in https://github.com/vmware-tanzu/community-edition/issues/1398 to resolve the BoM.

**Closed by joshrosso** 2022-03-28 21:42 UTC
Labels: kind/bug, area/core-eng, kind/test-release, area/release-eng
