### ISSUE TITLE
Concierge: build tooling to generate binaries

### ISSUE THREAD

**Issue by swalner-vmware** [vmware-tanzu/community-edition#3252] opened 2022-02-24 19:29 UTC
## Feature Request
Build out tooling that will create binaries (Windows, Mac, Linux) out of the PoC installer app

**Comment by miclettej** [comment] 2022-03-28 17:11
Closing as duplicate of https://github.com/vmware-tanzu/community-edition/issues/3631

**Closed by miclettej** 2022-03-28 17:11 UTC
Labels: kind/feature, area/installer
