### ISSUE TITLE
Deployment with http proxy not working

### ISSUE THREAD

**Issue by Excpt0r** [vmware-tanzu/community-edition#2752] opened 2021-12-23 17:53 UTC
Hi,

congrats for releasing TCE, that's a really easy option to try out and evaluate tanzu.
The installation works fine on my client machine, but not on a server that only has internet access through a proxy.

Here are my docker processes, after the mgmt cluster installation hangs at "Waiting for cert-manager to be available":
```
CONTAINER ID   IMAGE                                                         COMMAND                  CREATED          STATUS          PORTS                                  NAMES
04b4c3f4e524   projects.registry.vmware.com/tkg/kind/node:v1.21.2_vmware.1   "/usr/local/bin/entr\u2026"   2 minutes ago    Up 2 minutes                                           mymgmt-cluster-md-0-7f6466d5d7-dqlg4
f9d150cd65ff   projects.registry.vmware.com/tkg/kind/node:v1.21.2_vmware.1   "/usr/local/bin/entr\u2026"   46 minutes ago   Up 45 minutes   46357/tcp, 127.0.0.1:46357->6443/tcp   mymgmt-cluster-control-plane-dx9hf
7a348b598142   kindest/haproxy:v20210715-a6da3463                            "haproxy -sf 7 -W -d\u2026"   46 minutes ago   Up 46 minutes   45263/tcp, 0.0.0.0:45263->6443/tcp     mymgmt-cluster-lb
ad1953c96d96   projects.registry.vmware.com/tkg/kind/node:v1.21.2_vmware.1   "/usr/local/bin/entr\u2026"   47 minutes ago   Up 47 minutes   127.0.0.1:33479->6443/tcp              tkg-kind-c72aatuhoucjqqh2lim0-control-plane
```

The first process seems to be restarted regularly, and fails on downloading docker via curl:
```
root@mymgmt-cluster-md-0-7f6466d5d7-dqlg4:/# ps axu | grep -i curl
root         291  0.0  0.0   2612   536 ?        Ss   17:18   0:00 /bin/sh -c curl https://get.docker.com/builds/Linux/x86_64/docker-1.12.0.tgz | tar zxOf - docker/docker > /usr/local/bin/docker;chmod +x /usr/local/bin/docker
```

The configured TKG_HTTP_PROXY was inserted in the container at some places, but nothing that curl is evaluating (also no .bashrc or .curlrc entries), so the download fails.
```
root@mymgmt-cluster-control-plane-dx9hf:/# grep -R -i proxy /etc/
/etc/systemd/system/containerd.service.d/http-proxy.conf:Environment="HTTP_PROXY=http://X.X.X.X:YYYY"
/etc/systemd/system/containerd.service.d/http-proxy.conf:Environment="HTTPS_PROXY=http://X.X.X.X:YYYY"
/etc/systemd/system/containerd.service.d/http-proxy.conf:Environment="NO_PROXY=172.17.0.0/16,.svc.cluster.local,.svc,localhost,127.0.0.1,100.64.0.0/13,100.96.0.0/11,172.18.0.0/24"
/etc/systemd/system.conf.d/proxy-default-environment.conf:DefaultEnvironment="HTTP_PROXY=" "HTTPS_PROXY=" "NO_PROXY="
```

Anything I might be doing wrong or is that a bug?
I also had to add `TKG_NO_PROXY: 172.18.0.0/24`, otherwise the bootstrap cluster won't come up. Maybe that could be added automatically, like the other default CIDRs.

Btw, tanzu cluster create **--dry-run** is a nice feature.
Is that the right way to adjust the generated YAML config (i.e. to change default values for k8s processes like node-port range), and then use the YAML with kubectl create -f on the mgmt cluster?
If that's the intended way, it would be good to mention that in the installation docs.

**Comment by stmcginnis** [comment] 2022-01-03 11:53
May be related to https://github.com/vmware-tanzu/community-edition/issues/460 - but something else going on here.

**Comment by Excpt0r** [comment] 2022-01-09 10:57
Hi @stmcginnis 
thanks for pointing to the related ticket, I will have further reading, air-gapped installation is interesting for me too.
But having an internal image mirror will probably not solve the problem that curl cannot download the docker tar.gz

Does this ticket need any labels? I'm not allowed to add one.

**Comment by stmcginnis** [comment] 2022-01-10 15:28
> Does this ticket need any labels? I'm not allowed to add one.

Odd, that should have happened based on the type of issue you chose when creating. I've added a couple labels. We can refine once others have had a chance to triage it.

**Comment by joshrosso** [comment] 2022-01-13 21:20
@Excpt0r if this is reproducible, could you please use `tanzu diagnostics` plugin (https://tanzucommunityedition.io/docs/latest/tanzu-diagnostics/#collecting-diagnostics) to capture all the logs and upload them here for our review? This was we can understand what is getting hung up.

Be sure to run the diagnostics command when you are **in** this hung state.

**Comment by stmcginnis** [comment] 2022-01-22 21:44
Hi @Excpt0r - just wondering if you had a chance to run the `tanzu diagnostics` command like Josh suggested, or if things started working for you. Thanks!

**Comment by Excpt0r** [comment] 2022-01-26 12:06
Hi @stmcginnis 
I was able to reproduce the problem, the container `mymgmt-cluster-md-0-7f6466d5d7-g8pqd` keeps restarting,
and during the time it runs, I see again the executed command "curl https://get.docker.com/builds/Linux/x86_64/docker-1.12.0.tgz" that hangs.
My naive thought was that there would be a simple fix, to pass the proxy configuration to curl (via ENV, curlrc or maybe /etc/systemd/system.conf.d/proxy-default-environment.conf shouldn't have empty variables?).

Anyway, I also started the diagnostics tool, but it's too much data to review, and without that I can't publish here, sorry.
What I can give you is my installer config (mymgmt-cluster.yaml) to reproduce the problem, the install log and an overview of the bootstrap cluster state. Hope that is helpful enough.
Let me know if I should test any tweak or you need a specific log from the diagnostics.

[mymgmt-cluster.yaml.txt](https://github.com/vmware-tanzu/community-edition/files/7941537/mymgmt-cluster.yaml.txt)
[tanzu_install.log](https://github.com/vmware-tanzu/community-edition/files/7941538/tanzu_install.log)
[bootstrap_describe_mymgmt-cluster-md-0.txt](https://github.com/vmware-tanzu/community-edition/files/7941540/bootstrap_describe_mymgmt-cluster-md-0.txt)
[bootstrap_overview.txt](https://github.com/vmware-tanzu/community-edition/files/7941541/bootstrap_overview.txt)

**Comment by stmcginnis** [comment] 2022-01-26 19:54
Thanks @Excpt0r - still asking around. In the meantime, I was directed to a little more detailed proxy information than what we have in the  TCE docs. Could you take a look through this and see if there's anything standing out that's missing in your setup?

https://docs.vmware.com/en/VMware-Tanzu-Kubernetes-Grid/1.4/vmware-tanzu-kubernetes-grid-14/GUID-mgmt-clusters-create-config-file.html#proxies

**Comment by stmcginnis** [comment] 2022-01-26 20:02
OK, a little more information. Proxy-only access may not be a supported feature. The issue is we deploy various services into the cluster that themselves do not support proxy access for the things they need to do.

Will report back if I find out more details about that.

**Comment by Excpt0r** [comment] 2022-01-26 20:31
Thanks for the update.
I had a look at the proxy docs but don't see anything missing. The proxy does not need authentication, and vSphere is not involved.

Would also be interesting if this is a problem with TCE in combination with docker provider, TCE in general, or even TGK is not supporting airgapped environments.
Any docs about the technical difference between TCE and TKG would be appreciated.

**Comment by stmcginnis** [comment] 2022-01-26 21:09
> Any docs about the technical difference between TCE and TKG would be appreciated.

Other than some package versions, for the most part they are the same today. Which helps in that any existing docs for TKG that don't have an equivalent in the TCE docs yet can usually be followed with no difference.

If you wanted to try fully airgapped instead of going through a proxy, you could try these:

https://docs.vmware.com/en/VMware-Tanzu-Kubernetes-Grid/1.3/vmware-tanzu-kubernetes-grid-13/GUID-mgmt-clusters-airgapped-environments.html
https://cormachogan.com/2021/11/15/some-useful-tips-when-deploying-tkg-in-an-air-gap-environment/

**Comment by qnetter** [comment] 2022-01-26 21:42
TCE has a greater scope than TKG alone - its scope more corresponds to Tanzu Standard minus SaaS and proprietary components, and is on its way to being more like Tanzu Advanced minus SaaS and proprietary components.

**Comment by cjohnston23** [comment] 2022-02-24 23:20
This still seems to be a problem, I added 172.18.0.0/24 to be included as part of the TKG_NO_PROXY, but boostrap cluster still tried to use the proxies defined for TKG_HTTP_PROXY and TKG_HTTPS_PROXY.  I could easily see it failing to connect to the proxy in the pod logs.  My boostrap cluster is deploying on my laptop that doesn't have access to the required proxy where the management cluster gets deployed.  I want the proxy config for the management cluster, but not for the bootstrap.  Is there a fix for this?

**Closed** 2022-10-31 20:03 UTC
Labels: triage/needs-info, kind/support
