### ISSUE TITLE
Can't preview docs in edge in local hugo build

### ISSUE THREAD

**Issue by kcoriordan** [vmware-tanzu/community-edition#4060] opened 2022-04-15 13:46 UTC
## Bug Report
Can't preview docs in edge in local hugo build

## Steps to Reproduce the Bug

I run hugo server from \community-edition\docs\site>
And go to  //localhost:1313/
Select Documentation tab, which goes to http://localhost:1313/docs/v0.11
Get 404 for http://localhost:1313/docs/v0.11
Change link to http://localhost:1313/docs/edge – still get 404

I try steps in https://github.com/goharbor/website

from \community-edition\docs\site>
I run:
make preview

and also try

make production-build

make (e=2): The system cannot find the file specified.
make: *** [Makefile:5: prepare] Error 2

## Environment Details

* Build version (`tanzu version`): 
* Deployment (Managed/Unmanaged cluster): 
* Infrastructure Provider (Docker/AWS/Azure/vSphere): 
* Operating System (client):

**Comment by jpmcb** [comment] 2022-04-15 18:20
Is this a duplicate of https://github.com/vmware-tanzu/community-edition/issues/3687 ?

**Comment by kcoriordan** [comment] 2022-04-25 13:46
Ya - it's more or less a dup, I also tried other steps that @jonasrosland indicated are required for local build

> I try steps in https://github.com/goharbor/website

> from \community-edition\docs\site>
> I run:
> make preview
> 
> and also try
> 
> make production-build
> 
> make (e=2): The system cannot find the file specified.
> make: *** [Makefile:5: prepare] Error 2

**Comment by jonasrosland** [comment] 2022-04-26 20:13
@a-mccarthy will be taking a look at this!

**Closed** 2022-05-25 16:39 UTC
Labels: kind/bug
