### ISSUE TITLE
Errors running vsphere-cpi unit tests

### ISSUE THREAD

**Issue by stmcginnis** [vmware-tanzu/community-edition#4185] opened 2022-04-25 19:53 UTC
## Bug Report

Errors seen running both the 1.23.0-alpha.1 and 1.23.0 package unit tests:

```
vSphere CPI Ytt Templates vsphere-cloud-config ConfigMap INI file Deprecate insecureFlag and remoteAuth when insecureFlag and remoteAuth are set 
  correctly sets the value in the INI
  /home/smcginnis/src/vmware-tanzu/community-edition/addons/packages/vsphere-cpi/1.23.0-alpha.1/test/vsphere_cpi_test.go:609

• Failure [0.010 seconds]
vSphere CPI Ytt Templates
/home/smcginnis/src/vmware-tanzu/community-edition/addons/packages/vsphere-cpi/1.23.0-alpha.1/test/vsphere_cpi_test.go:24
  vsphere-cloud-config ConfigMap INI file
  /home/smcginnis/src/vmware-tanzu/community-edition/addons/packages/vsphere-cpi/1.23.0-alpha.1/test/vsphere_cpi_test.go:266
    Deprecate insecureFlag and remoteAuth
    /home/smcginnis/src/vmware-tanzu/community-edition/addons/packages/vsphere-cpi/1.23.0-alpha.1/test/vsphere_cpi_test.go:585
      when insecureFlag and remoteAuth are set
      /home/smcginnis/src/vmware-tanzu/community-edition/addons/packages/vsphere-cpi/1.23.0-alpha.1/test/vsphere_cpi_test.go:586
        correctly sets the value in the INI [It]
        /home/smcginnis/src/vmware-tanzu/community-edition/addons/packages/vsphere-cpi/1.23.0-alpha.1/test/vsphere_cpi_test.go:609

        Unexpected error:
            <exec.CodeExitError>: {
                Err: <*errors.errorString | 0xc000355f60>{
                    s: "error running /home/smcginnis/bin/ytt --ignore-unknown-comments -f /home/smcginnis/src/vmware-tanzu/community-edition/addons/packages/vsphere-cpi/1.23.0-alpha.1/bundle/config/upstream/vsphere-cpi/01-rbac.yaml -f /home/smcginnis/src/vmware-tanzu/community-edition/addons/packages/vsphere-cpi/1.23.0-alpha.1/bundle/config/upstream/vsphere-cpi/02-config.yaml -f /home/smcginnis/src/vmware-tanzu/community-edition/addons/packages/vsphere-cpi/1.23.0-alpha.1/bundle/config/upstream/vsphere-cpi/03-secret.yaml -f /home/smcginnis/src/vmware-tanzu/community-edition/addons/packages/vsphere-cpi/1.23.0-alpha.1/bundle/config/upstream/vsphere-cpi/04-daemonset.yaml -f /home/smcginnis/src/vmware-tanzu/community-edition/addons/packages/vsphere-cpi/1.23.0-alpha.1/bundle/config/overlays/vsphere-cpi/update-config.yaml -f /home/smcginnis/src/vmware-tanzu/community-edition/addons/packages/vsphere-cpi/1.23.0-alpha.1/bundle/config/overlays/vsphere-cpi/add-secret.yaml -f /home/smcginnis/src/vmware-tanzu/community-edition/addons/packages/vsphere-cpi/1.23.0-alpha.1/bundle/config/overlays/vsphere-cpi/update-secret.yaml -f /home/smcginnis/src/vmware-tanzu/community-edition/addons/packages/vsphere-cpi/1.23.0-alpha.1/bundle/config/overlays/vsphere-cpi/update-daemonset.yaml -f /home/smcginnis/src/vmware-tanzu/community-edition/addons/packages/vsphere-cpi/1.23.0-alpha.1/bundle/config/upstream/vsphere-paravirtual-cpi/01-rbac.yaml -f /home/smcginnis/src/vmware-tanzu/community-edition/addons/packages/vsphere-cpi/1.23.0-alpha.1/bundle/config/upstream/vsphere-paravirtual-cpi/02-config.yaml -f /home/smcginnis/src/vmware-tanzu/community-edition/addons/packages/vsphere-cpi/1.23.0-alpha.1/bundle/config/upstream/vsphere-paravirtual-cpi/03-deployment.yaml -f /home/smcginnis/src/vmware-tanzu/community-edition/addons/packages/vsphere-cpi/1.23.0-alpha.1/bundle/config/overlays/vsphere-paravirtual-cpi/update-deployment.yaml -f /home/smcginnis/src/vmware-tanzu/community-edition/addons/packages/vsphere-cpi/1.23.0-alpha.1/bundle/config/values.yaml -f /home/smcginnis/src/vmware-tanzu/community-edition/addons/packages/vsphere-cpi/1.23.0-alpha.1/bundle/config/values.star -f /home/smcginnis/src/vmware-tanzu/community-edition/addons/packages/vsphere-cpi/1.23.0-alpha.1/bundle/config/vsphereconf.lib.txt -f -:\nCommand stdout:\n\nstderr:\nytt: Error: Overlaying data values (in following order: values.yaml, stdin.yml):\n  Templating file 'stdin.yml': \n- __ytt_tpl3_start_node: expected key 'insecureFlag' to not be specified again (unless 'yaml/map-key-override' annotation is added)\n    in <toplevel>\n      stdin.yml:18 | insecureFlag: \"true\"\n\nerror:\nexit status 1",
                },
                Code: 1,
            }
            error running /home/smcginnis/bin/ytt --ignore-unknown-comments -f /home/smcginnis/src/vmware-tanzu/community-edition/addons/packages/vsphere-cpi/1.23.0-alpha.1/bundle/config/upstream/vsphere-cpi/01-rbac.yaml -f /home/smcginnis/src/vmware-tanzu/community-edition/addons/packages/vsphere-cpi/1.23.0-alpha.1/bundle/config/upstream/vsphere-cpi/02-config.yaml -f /home/smcginnis/src/vmware-tanzu/community-edition/addons/packages/vsphere-cpi/1.23.0-alpha.1/bundle/config/upstream/vsphere-cpi/03-secret.yaml -f /home/smcginnis/src/vmware-tanzu/community-edition/addons/packages/vsphere-cpi/1.23.0-alpha.1/bundle/config/upstream/vsphere-cpi/04-daemonset.yaml -f /home/smcginnis/src/vmware-tanzu/community-edition/addons/packages/vsphere-cpi/1.23.0-alpha.1/bundle/config/overlays/vsphere-cpi/update-config.yaml -f /home/smcginnis/src/vmware-tanzu/community-edition/addons/packages/vsphere-cpi/1.23.0-alpha.1/bundle/config/overlays/vsphere-cpi/add-secret.yaml -f /home/smcginnis/src/vmware-tanzu/community-edition/addons/packages/vsphere-cpi/1.23.0-alpha.1/bundle/config/overlays/vsphere-cpi/update-secret.yaml -f /home/smcginnis/src/vmware-tanzu/community-edition/addons/packages/vsphere-cpi/1.23.0-alpha.1/bundle/config/overlays/vsphere-cpi/update-daemonset.yaml -f /home/smcginnis/src/vmware-tanzu/community-edition/addons/packages/vsphere-cpi/1.23.0-alpha.1/bundle/config/upstream/vsphere-paravirtual-cpi/01-rbac.yaml -f /home/smcginnis/src/vmware-tanzu/community-edition/addons/packages/vsphere-cpi/1.23.0-alpha.1/bundle/config/upstream/vsphere-paravirtual-cpi/02-config.yaml -f /home/smcginnis/src/vmware-tanzu/community-edition/addons/packages/vsphere-cpi/1.23.0-alpha.1/bundle/config/upstream/vsphere-paravirtual-cpi/03-deployment.yaml -f /home/smcginnis/src/vmware-tanzu/community-edition/addons/packages/vsphere-cpi/1.23.0-alpha.1/bundle/config/overlays/vsphere-paravirtual-cpi/update-deployment.yaml -f /home/smcginnis/src/vmware-tanzu/community-edition/addons/packages/vsphere-cpi/1.23.0-alpha.1/bundle/config/values.yaml -f /home/smcginnis/src/vmware-tanzu/community-edition/addons/packages/vsphere-cpi/1.23.0-alpha.1/bundle/config/values.star -f /home/smcginnis/src/vmware-tanzu/community-edition/addons/packages/vsphere-cpi/1.23.0-alpha.1/bundle/config/vsphereconf.lib.txt -f -:
            Command stdout:
            
            stderr:
            ytt: Error: Overlaying data values (in following order: values.yaml, stdin.yml):
              Templating file 'stdin.yml': 
            - __ytt_tpl3_start_node: expected key 'insecureFlag' to not be specified again (unless 'yaml/map-key-override' annotation is added)
                in <toplevel>
                  stdin.yml:18 | insecureFlag: "true"
            
            error:
            exit status 1
        occurred

        /home/smcginnis/src/vmware-tanzu/community-edition/addons/packages/vsphere-cpi/1.23.0-alpha.1/test/vsphere_cpi_test.go:610
------------------------------


Summarizing 1 Failure:

[Fail] vSphere CPI Ytt Templates vsphere-cloud-config ConfigMap INI file Deprecate insecureFlag and remoteAuth when insecureFlag and remoteAuth are set [It] correctly sets the value in the INI 
/home/smcginnis/src/vmware-tanzu/community-edition/addons/packages/vsphere-cpi/1.23.0-alpha.1/test/vsphere_cpi_test.go:610

Ran 29 of 29 Specs in 1.046 seconds
FAIL! -- 28 Passed | 1 Failed | 0 Pending | 0 Skipped
```

## Expected Behavior

Unit tests should run with no failures.

## Steps to Reproduce the Bug

```
cd addons/packages/vsphere-cpi/1.23.0/test
go run github.com/onsi/ginkgo/ginkgo -v .
```

**Comment by stmcginnis** [comment] 2022-04-26 12:27
@lubronzhan is this something you can take a look at?

**Comment by dvonthenen** [comment] 2022-04-29 16:39
hey @vmware-tanzu/pkg-vsphere-cpi-owners do you mind taking a look a this?

**Comment by lubronzhan** [comment] 2022-04-30 05:46
I think it was fixed by this? https://github.com/vmware-tanzu/community-edition/pull/4135

**Comment by stmcginnis** [comment] 2022-04-30 12:54
Yep, testing locally, that appears to have fixed the test failures.

I can push up a change to reenable running the tests.

**Comment by HanFa** [comment] 2022-05-02 17:30
Yes, this was caused by the wrong indentation of testdata yaml. And https://github.com/vmware-tanzu/community-edition/pull/4135 should fix it.

**Closed** 2022-05-02 19:25 UTC
Labels: kind/bug, area/packages
